ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER sibintech_normal IDENTIFIED BY "sibintech_pass";
GRANT CONNECT TO sibintech_normal;
GRANT CONNECT, RESOURCE, DBA TO sibintech_normal;
GRANT CREATE SESSION, GRANT ANY PRIVILEGE TO sibintech_normal;
GRANT UNLIMITED TABLESPACE TO sibintech_normal;
GRANT CREATE ANY TABLE TO sibintech_normal;
CREATE TABLE SIBINTECH_NORMAL.FILES_CONTENT
(
  FILES_CONTENT_ID  NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
  FILE_NAME         VARCHAR2(2000 BYTE),
  FILE_PATH         VARCHAR2(2000 BYTE),
  FILE_ERROR        VARCHAR2(2000 BYTE),
  FILE_HASH         VARCHAR2(2000 BYTE)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON SIBINTECH_NORMAL.FILES_CONTENT TO sibintech_normal;